#!/bin/bash

python run_train_baselines.py -config MRT_largeset_small_scale_type_2
python run_train_baselines.py -config MRT_largeset_small_scale_type_6
python run_train_baselines.py -config MRT_monitor_largeset_small_scale_type_2
python run_train_baselines.py -config MRT_monitor_largeset_small_scale_type_6
