batch_size: 10
check_tangle_interval: 10
cluster_r: 0.35
conv_feat:
- conv_uh
- conv_hessian_norm
conv_feat_fix:
- conv_uh_fix
count_tangle_method: inversion
data_root: ./data/helmholtz/
inversion_loss_scaler: 10000000000.0
is_normalise: true
learning_rate: 5.0e-05
mesh_feat:
- coord
- u
- hessian_norm
model_used: MRTransformer
multi_scale_check_interval: 50
n_grids:
- 15
- 20
n_grids_test:
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
num_deform_in: 7
num_deformer_loop: 1
num_epochs: 1000
num_gfe_in: 2
num_lfe_in: 4
num_transformer_in: 4
num_transformer_out: 16
num_transformer_embed_dim: 64
num_transformer_heads: 4
num_transformer_layers: 1
transformer_training_mask: true
transformer_training_mask_portion: 0.95
out_path: ./out
print_interval: 1
project: warpmesh
save_interval: 20
train_boundary_scheme: full
train_data_set_type: aniso
use_area_loss: true
use_cluster: false
use_inversion_diff_loss: false
use_inversion_loss: false
use_jacob: false
weight_decay: 0.1
x_feat:
- coord
- bd_mask
- bd_left_mask
- bd_right_mask
- bd_down_mask
- bd_up_mask
