name: build docs

on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main

jobs:
  build_docs:
    runs-on: ubuntu-22.04
    container:
      image: firedrakeproject/firedrake:latest
      options: --user root

    steps:
    - name: Checkout warpmesh
      uses: actions/checkout@v3
    - name: Install movement
      run: |
          git clone https://github.com/pyroteus/movement.git
          cd movement
          pip install -e .
    - name: Install warpmesh
      run: |
          . /home/firedrake/firedrake/bin/activate
          pwd
          pip install -e .
    - name: install warpmesh dependencies
      run: |
          . /home/firedrake/firedrake/bin/activate
          pip install -r requirements.txt
    - name: Build docs using sphinx
      run: |
        . /home/firedrake/firedrake/bin/activate
        sphinx-build -b html docs docs/html
    - name: Commit files
      run: |
        ls -al
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global --add safe.directory /__w/WarpMesh/WarpMesh
        git status
        git add docs/html
        git status
        git commit -m "docs auto generated"
    - name: Push files to repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}