name: Install and Test WarpMesh

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test-warpmesh:
    name: Test WarpMesh
    runs-on: ubuntu-22.04
    container:
      image: firedrakeproject/firedrake:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Install Movement
        run: |
          . /home/firedrake/firedrake/bin/activate
          git clone https://github.com/mesh-adaptation/movement.git
          cd movement
          pip install -e .
      - name: Install other WarpMesh dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          pip install -r requirements.txt
      - name: Install WarpMesh
        run: |
          . /home/firedrake/firedrake/bin/activate
          pip install -e .
      - name: Run WarpMesh test suite
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pytest tests/test* -v
