name: Install and Test WarpMesh

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test-warpmesh:
    name: Test WarpMesh
    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3

      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Movement
        run: |
          . /home/firedrake/firedrake/bin/activate
          git clone https://github.com/mesh-adaptation/movement.git
          cd movement
          python3 -m pip install -e .

      - name: Install PyTorch
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Install PyTorch3d
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pip install 'git+https://github.com/facebookresearch/pytorch3d.git'

      - name: Install WarpMesh
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pip install -e .

      - name: Lint check
        if: ${{ always() }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          ruff check

      - name: Run WarpMesh test suite
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pytest tests/test* -v
